import type { Metadata } from 'next';
import Navbar from '@/components/navbar';
import Footer from '@/components/footer';

export const metadata: Metadata = {
  title: 'Terms of Service',
  description: 'Terms of Service for MyAIJourney.org. Please read these terms before using our website.',
};

export default function TermsPage() {
  return (
    <>
      <Navbar />
      <main>
        <section
          style={{
            background: 'linear-gradient(135deg, #EFF6FF 0%, #F8FAFC 100%)',
            padding: '56px 0 40px',
            borderBottom: '1px solid var(--color-border)',
          }}
        >
          <div className="container">
            <h1 style={{ fontFamily: 'var(--font-heading)', fontSize: '2.2rem', fontWeight: 700 }}>Terms of Service</h1>
            <p style={{ color: 'var(--color-text-muted)', marginTop: '8px' }}>Last updated: May 2025</p>
          </div>
        </section>
        <section className="section">
          <div className="container" style={{ maxWidth: '800px', margin: '0 auto' }}>
            <div className="prose">
              <h2>Acceptance of Terms</h2>
              <p>By accessing and using MyAIJourney.org ("the Site"), you accept and agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the Site.</p>

              <h2>Content and Opinions</h2>
              <p>All reviews, articles, and opinions expressed on MyAIJourney are those of the author, Jim Harrell, based on personal testing and experience. Content is provided for informational purposes only and should not be taken as professional advice.</p>
              <p>While we strive to provide accurate and up-to-date information, AI tools and their features change frequently. Pricing, features, and availability mentioned in reviews may change after publication.</p>

              <h2>Affiliate Links and Compensation</h2>
              <p>MyAIJourney participates in affiliate programs. This means that when you click certain links on our site and make a purchase, we may earn a commission at no additional cost to you. Affiliate relationships do not influence our reviews or recommendations. We only recommend tools we have personally tested and believe provide value.</p>

              <h2>Intellectual Property</h2>
              <p>All content on MyAIJourney, including text, graphics, logos, and images, is the property of MyAIJourney and is protected by copyright laws. You may not reproduce, distribute, or create derivative works from our content without explicit written permission.</p>

              <h2>User Conduct</h2>
              <p>When using our contact form, newsletter signup, or AI chat assistant, you agree not to:</p>
              <ul>
                <li>Submit false or misleading information</li>
                <li>Use automated systems to scrape or harvest data from the Site</li>
                <li>Attempt to interfere with the proper functioning of the Site</li>
                <li>Use the AI chat assistant for purposes that violate applicable laws</li>
              </ul>

              <h2>AI Chat Assistant</h2>
              <p>Our AI chat assistant is provided for informational purposes to help you navigate AI tool choices. Responses are generated by artificial intelligence and may not always be accurate or up to date. Do not rely solely on the chat assistant for critical purchasing decisions.</p>
              <p>By using the chat assistant, you acknowledge that:</p>
              <ul>
                <li>Responses are generated by AI (OpenAI GPT models) and may contain inaccuracies</li>
                <li>The assistant may reference product features, pricing, or availability that has changed since its training data was compiled</li>
                <li>Recommendations are general in nature and may not account for your specific technical requirements, budget constraints, or use case</li>
                <li>We are not liable for any decisions made based on AI chat responses</li>
              </ul>

              <h2>AI-Generated and AI-Assisted Content</h2>
              <p>MyAIJourney may use AI tools to assist in content creation (drafting, research, formatting). All published content is reviewed, verified, and approved by a human editor before publication. AI assistance does not diminish the editorial integrity or accuracy of our reviews. Our ratings, recommendations, and opinions are based on genuine hands-on human testing.</p>

              <h2>No Professional Advice</h2>
              <p>Content on this site, including AI tool reviews, comparisons, and chat assistant responses, is for <strong>informational purposes only</strong>. It does not constitute professional, legal, financial, or technical advice. Always conduct your own due diligence before purchasing software or making business decisions based on content found on this site.</p>

              <h2>Newsletter</h2>
              <p>By subscribing to our newsletter, you consent to receive periodic emails about AI tool reviews and related content. You may unsubscribe at any time using the link provided in each email.</p>

              <h2>Limitation of Liability</h2>
              <p>MyAIJourney and its owner shall not be liable for any direct, indirect, incidental, or consequential damages arising from your use of the Site, its content, or any products or services purchased through affiliate links.</p>

              <h2>Third-Party Links</h2>
              <p>The Site contains links to third-party websites. We are not responsible for the content, privacy practices, or terms of service of these external sites.</p>

              <h2>Changes to Terms</h2>
              <p>We reserve the right to update these Terms of Service at any time. Changes will be posted on this page with an updated date. Continued use of the Site after changes are posted constitutes acceptance of the modified terms.</p>

              <h2>Governing Law</h2>
              <p>These terms shall be governed by and construed in accordance with the laws of the United States of America.</p>

              <h2>Contact</h2>
              <p>For questions about these terms, contact us at <a href="mailto:support@myaijourney.org">support@myaijourney.org</a> or through our <a href="/contact">contact page</a>.</p>
            </div>
          </div>
        </section>
      </main>
      <Footer />
    </>
  );
}




